# Rutas manuales
pokemon_list_pokemons:
    path: /pokemones
    controller: App\Pokemon\infrastructure\PokemonController::listPokemons
    methods: [GET]

pokemon_find_pokemon:
    path: /pokemones/{name}
    controller: App\Pokemon\infrastructure\PokemonController::findPokemon
    methods: [GET]