# Rutas manuales
pokemon_list_pokemons:
    path: /pokemons
    controller: App\Pokemon\infrastructure\PokemonController::listPokemons
    methods: [GET]

pokemon_find_pokemon:
    path: /pokemons/{name}
    controller: App\Pokemon\infrastructure\PokemonController::findPokemon
    methods: [GET]