# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # Para que todas las clases en src/Pokemon/infrastructure/
    # (controladores, comandos, etc.) sean servicios.
    App\Pokemon\infrastructure\:
        resource: '../src/Pokemon/infrastructure/'
        # Excluimos el directorio de Doctrine para evitar conflictos en la inyección de dependencias
        # Y para que los comandos de Doctrine funcionen sin problemas.
        exclude: '../src/Pokemon/infrastructure/Doctrine'

    # Configuración específica para el repositorio de Doctrine
    # como un servicio para que pueda ser inyectado.
    App\Pokemon\infrastructure\Doctrine\Repository\PokemonRepository:
        public: true
        tags: [ 'doctrine.repository_service' ]

    # Clases de la capa de aplicación (servicios) sean servicios.
    App\Pokemon\application\:
        resource: '../src/Pokemon/application/'

    # Clases de la capa de dominio sean servicios.
    App\Pokemon\domain\:
        resource: '../src/Pokemon/domain/'

    # Cuando alguien pida la interfaz 'PokemonRepositoryInterface',
    # siempre dale una instancia del repositorio de Doctrine.
    App\Pokemon\domain\PokemonRepositoryInterface:
        alias: App\Pokemon\infrastructure\Doctrine\Repository\PokemonRepository